// AUTOGENERATED. DO NOT EDIT. INVOKE 'make' TO REGENERATE.

#include "quotes.h"

static char const *const QUOTES[] = {
#include "quotes.txt" /* If using Arudino on winodws, you'll need to enter full path */
};

int const NUM_QUOTES = 403;
